[
   Module                   -- KW["module"] _1 KW["{"] _2 KW["}"],
   Module.2:iter-star       -- _1,
   Class                    -- KW["class"] _1 KW["{"] _2 KW["}"],
   Class.2:iter-star        -- _1,
   Field                    -- _1,
   Method                   -- _1 KW["("] _2 KW[")"] KW[":"] _3 KW["{"] _4 KW["}"],
   Method.2:iter-star-sep   -- _1 KW[","],
   Method.4:iter-star       -- _1,
   Method.4:iter-star.1:seq -- _1 KW[";"],
   Declare                  -- KW["var"] _1 KW[":"] _2,
   Assign                   -- _1 KW["="] _2,
   Return                   -- KW["return"] _1,
   Call                     -- _1 KW["."] _2 KW["("] _3 KW[")"],
   Call.3:iter-star-sep     -- _1 KW[","],
   Id                       -- _1,
   New                      -- KW["new"] _1 KW["()"],
   NatConst                 -- _1,
   Add                      -- _1 KW["+"] _2,
   Sub                      -- _1 KW["-"] _2,
   Mul                      -- _1 KW["*"] _2,
   NT                       -- _1 KW[":"] _2,
   NatType                  -- KW["nat"],
   ClassType                -- _1,
   RefCascade               -- _1,
   RefCascade.1:iter-sep    -- _1 KW["."]
]